baseURL = "https://davidtranscend.com/blog"
languageCode = "en-us"
title = "David Tran's Blog"
theme = "casper"
paginate = 5
Copyright = "© {year}"
canonifyurls = true

[params]
  description = "A day in the life of a software developer"
  # metadescription = "Used as 'description' meta tag for both home and index pages. If not set, 'description' will be used instead"
  cover = "images/cover.jpg"
  author = "David Tran"
  authorlocation = "Southern California"
  authorwebsite = "https://davidtranscend.com"
  authorbio= "David is a software developer with experience in web technologies and interest in software and hardware integration. He is a lifelong learner, an avid podcast listener, and an enthusiast of books of all genres."
  authoravatar = "images/david.png"
  # logo = "images/logo.png"
  googleAnalyticsUserID = "UA-79101-12" # TODO: Get analytics ID
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feeds.feedburner.com/..." # TODO: Sign up for feedburner
  githubName = "davidlamt"
  twitterName = "davidlamt"
  linkedinName = "davidlamt"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false

  # Setting a value will load highlight.js and enable syntax highlighting using the style selected.
  # See https://github.com/isagalaev/highlight.js/tree/master/src/styles for available styles
  # A preview of above styles can be viewed at https://highlightjs.org/static/demo/
  hjsStyle = "github-gist"

  [params.social]
    twitter = "your_twitter"
